package net.juniper.jmp.persist.jdbc;

import java.io.Serializable;
import java.util.List;
import java.util.Map;
/**
 * Mapping Data for Entity Object
 * @author juntaod
 *
 */
public interface IMappingMeta extends Serializable {
   
    public String getPrimaryKey();
    
    public boolean isAutoGeneratedPk();

    public String getTableName();
    
    public String getVersionName();

    public List<FieldMeta> getEntityFields();
    
    public Map<String, FieldMeta> getColumnFieldMap();
    
    public Map<String, FieldMeta> getFieldFieldMap();
    
    public Map<String, Integer> getColumnTypeMap();
    
    public String[] getValidFields();

	public String[] getValidFieldsWithoutPk();

	public FieldMeta getFieldMetaByColumn(String column);
	
	public Object getEntity();
}