package net.juniper.jmp.persist.impl;

import java.lang.ref.Reference;
import java.lang.ref.WeakReference;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import net.juniper.jmp.persist.jdbc.FieldMeta;
import net.juniper.jmp.persist.jdbc.IMappingMeta;
/**
 * Mapping information from one Entity Object to one Db table
 * @author juntaod
 *
 * @param <T>
 */
public abstract class MappingMeta<T> implements IMappingMeta {
	private static final long serialVersionUID = -3192362496510980507L;
	private String primaryKey;
	private boolean autoGeneratedPk = true;
	private String tableName;
	private String versionName;
	private Map<String, FieldMeta> columnFieldMap;
	private Map<String, FieldMeta> fieldFieldMap;
	private List<FieldMeta> entityFields;
	private String[] validFieldsWithoutPk;
	private String[] validFields;
	private Reference<Class<T>> entityRef;
	private Map<String, Integer> columnTypeMap;
	public MappingMeta(String dataSource, Class<T> entity){
		if(entity != null){
			entityRef = new WeakReference<Class<T>>(entity);
			resolve(dataSource, entity);
		}
	}
	
	@Override
	public Object getEntity() {
		return entityRef.get();
	}
	
	@Override
	public String getPrimaryKey() {
		return primaryKey;
	}

	@Override
	public String getTableName() {
		return tableName;
	}

	@Override
	public List<FieldMeta> getEntityFields() {
		return entityFields;
	}

	@Override
	public String[] getValidFields() {
		if(validFields == null){
			validFields = getFieldFieldMap().keySet().toArray(new String[0]);
		}
		return validFields;
	}

	@Override
	public String[] getValidFieldsWithoutPk() {
		if(validFieldsWithoutPk == null){
			Set<String> fieldSet = new HashSet<String>();
			fieldSet.addAll(getFieldFieldMap().keySet());
			fieldSet.remove(getPrimaryKey());
			validFieldsWithoutPk = fieldSet.toArray(new String[0]);
		}
		return validFieldsWithoutPk;
	}

	@Override
	public FieldMeta getFieldMetaByColumn(String column) {
		if(entityFields == null)
			return null;
		columnFieldMap = getColumnFieldMap();
		return columnFieldMap.get(column);
	}
	
	protected abstract void resolve(String dataSource, Class<T> entity);

	@Override
	public Map<String, FieldMeta> getColumnFieldMap() {
		if(columnFieldMap == null){
			columnFieldMap = new HashMap<String, FieldMeta>();
			for (int i = 0; i < entityFields.size(); i++) {
				FieldMeta fm = entityFields.get(i);
				columnFieldMap.put(fm.getColumn(), fm);
			}
		}
		return columnFieldMap;
	}

	public void setColumnFieldMap(Map<String, FieldMeta> columnFieldMap) {
		this.columnFieldMap = columnFieldMap;
	}

	@Override
	public Map<String, FieldMeta> getFieldFieldMap() {
		if(fieldFieldMap == null){
			fieldFieldMap = new HashMap<String, FieldMeta>();
			for (int i = 0; i < entityFields.size(); i++) {
				FieldMeta fm = entityFields.get(i);
				fieldFieldMap.put(fm.getField(), fm);
			}
		}
		return fieldFieldMap;
	}

	public void setFieldFieldMap(Map<String, FieldMeta> fieldFieldMap) {
		this.fieldFieldMap = fieldFieldMap;
	}

	public String[] getValieFields() {
		return validFields;
	}

	public void setPrimaryKey(String primaryKey) {
		this.primaryKey = primaryKey;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	public void setEntityFields(List<FieldMeta> entityFields) {
		this.entityFields = entityFields;
	}

	public void setValidFieldsWithoutPk(String[] validFieldsWithoutPk) {
		this.validFieldsWithoutPk = validFieldsWithoutPk;
	}

	@Override
	public String getVersionName() {
		return versionName;
	}

	public void setVersionName(String versionName) {
		this.versionName = versionName;
	}

	@Override
	public Map<String, Integer> getColumnTypeMap() {
		return columnTypeMap;
	}
	
	public void setColumnTypeMap(Map<String, Integer> columnTypeMap){
		this.columnTypeMap = columnTypeMap;
	}

	public boolean isAutoGeneratedPk() {
		return autoGeneratedPk;
	}

	public void setAutoGeneratedPk(boolean autoGeneratedPk) {
		this.autoGeneratedPk = autoGeneratedPk;
	}
}
